maro/rl/storage/column_based_store.py, tests/test_store.py
fixed unpicklable store bug and incorrect method name in test_store
=> V0.1 test store update

examples/cim/dqn/single_process_launcher.py
fixed a key error in K-step shaper for CIM
=> fixed a key error in K-step shaper for CIM

maro/rl/shaping/k_step_experience_shaper.py
fixed unpicklable bug in k step shaper
=> fixed unpicklable bug in k step shaper

examples/cim/dqn/README.md
=> removed sentence above title

maro/utils/utils.py
update api docs of maro.utils.utils
=> update api docs of maro.utils.utils

docs/source/apidoc/maro.rl.rst, maro/rl/actor/abs_actor.py, maro/rl/agent/abs_agent.py, maro/rl/agent/abs_agent_manager.py, maro/rl/algorithms/torch/abs_algorithm.py, maro/rl/explorer/abs_explorer.py, maro/rl/explorer/simple_explorer.py, maro/rl/learner/abs_learner.py, maro/rl/learner/simple_learner.py, maro/rl/storage/column_based_store.py
added more doctstrings in RL toolkit
=> added more doctstrings in RL toolkit

CONTRIBUTING.md, maro/cli/grass/data.py, maro/cli/grass/executors/grass_azure_executor.py, maro/cli/grass/utils/copy.py, maro/cli/k8s/executors/k8s_azure_executor.py, maro/cli/maro.py, maro/cli/utils/copy.py, maro/cli/utils/params.py, tests/cli/config.yml, tests/cli/grass/test_data/README.md, tests/cli/grass/test_grass.py, tests/cli/k8s/test_data/README.md, tests/cli/k8s/test_k8s.py, tests/cli/speed/test_grass_copy.py, tests/cli/speed/test_k8s_copy.py, tests/cli/templates/test_grass_azure_create.yml, tests/cli/templates/test_k8s_azure_create.yml
- CLI pull/push data refactoring
- CLI integration test
- [pr 138](https://github.com/microsoft/maro/pull/138)
- OS:
=> V0.1: CLI pull/push data refactoring with integration test

docs/source/installation/k8s_cluster_provisioning_on_azure.rst, examples/cim/dqn/dist_actor.py, examples/cim/dqn/dist_learner.py, maro/cli/grass/executors/grass_azure_executor.py, maro/cli/k8s/executors/k8s_azure_executor.py, maro/cli/k8s/job.py, maro/cli/k8s/lib/k8s_configs/job.yml, maro/cli/maro.py, maro/utils/logger.py, tests/cli/grass/test_data/README.md, tests/cli/grass/test_grass.py, tests/cli/k8s/test_data/README.md, tests/cli/k8s/test_k8s.py, tests/cli/templates/test_grass_azure_start_job_dqn.yml, tests/cli/templates/test_k8s_azure_start_job_dqn.yml
1. add docs for AzCopy
2. add dqn tests in grass/k8s mode 
- OS:
=> V0.1 issues in CLI

maro/cli/grass/executors/grass_azure_executor.py, maro/cli/grass/executors/grass_executor.py, maro/cli/grass/lib/agents/exception.py, maro/cli/grass/lib/agents/master_agent.py, maro/cli/grass/lib/agents/node_agent.py, maro/cli/grass/lib/agents/resource.py, maro/cli/grass/lib/agents/utils.py, maro/cli/grass/lib/scripts/create_killed_job_ticket.py, maro/cli/grass/lib/scripts/create_pending_job_ticket.py, maro/cli/grass/lib/scripts/delete_pending_job_ticket.py, maro/cli/grass/lib/scripts/get_containers_details.py, maro/cli/grass/lib/scripts/load_master_agent_service.py, maro/cli/grass/lib/scripts/utils.py, maro/cli/utils/executors/azure_executor.py, maro/utils/checkpoint.py, setup.py, tests/checkpoint/config.yml, tests/checkpoint/test_checkpoint.py, tests/checkpoint/test_checkpoint_parameters.json, tests/checkpoint/test_checkpoint_template.json
Checkpoint and recovery agent for proxy rejoin
- [130](https://github.com/microsoft/maro/issues/130)
- OS:
=> Checkpoint and recovery agent

maro/rl/dist_topologies/common.py, maro/rl/dist_topologies/single_learner_multi_actor_sync_mode.py
Bug fix for SimpleLearner's test function. 
- OS:
=> v0.2_learner_test_bug_fix

maro/data_lib/dump_csv_converter.py
Enhanced manifest file format. It auto generate manifest file after dump.
It needed to run scripts/build_maro.sh before effective.
- OS:
=> Added manifest file.

examples/vm_scheduling/best_fit/launcher.py
In the example of Best Fit algorithm, update the usage of snapshot: access once to get info of all valid pms.
- OS:
=> best fit example: update the usage of snapshot

maro/simulator/scenarios/vm_scheduling/business_engine.py
Add the short logic to process None action.
- OS:
=> V0.2 Resolve none action problem

README.md
Fix README.md spelling typo.
- OS:
=> Fix readme spelling typo

docs/source/scenarios/vm_scheduling.rst
=> v0.2 VM Scheduling docs refinement

maro/simulator/scenarios/vm_scheduling/business_engine.py
Fix bugs due to the error event name.
- OS:
=> v0.2 vm Fix bug

maro/data_lib/dump_csv_converter.py, maro/rl/algorithms/dqn.py, maro/rl/storage/column_based_store.py
=> syntax fix

README.md, notebooks/articles/simple_bike_repositioning.ipynb
- env setup added for simple bike repositioning
- PYTHONPATH setup added in README
- OS:
=> env setup added for simple bike repositioning

maro/simulator/scenarios/vm_scheduling/business_engine.py, maro/simulator/scenarios/vm_scheduling/common.py
1. Fix the data preparation bug.
2. Add frame index into decision event (payload).
- OS:
=> V0.2 vm scheduling decision event

docs/source/scenarios/vm_scheduling.rst
fix a typo in the vm_scheduling.rst
=> fix doc typo

examples/cim/dqn/dist_actor.py
Issue#264 bug fix
- [264](https://github.com/microsoft/maro/issues/264)
- OS:
=> issue#264 bug fix

README.md
=> Update master readme links

.github/workflows/build_wheel.yml, .github/workflows/deploy_docker_image.yml, .github/workflows/deploy_gh_pages.yml, .github/workflows/test.yml, maro/backends/raw_backend.pyx, scripts/compile_cython.bat, scripts/compile_cython.sh
Use generated raw_backend.pyx file instead realtime generating from template, as backend code not always change.
- OS:
=> change the way to build maro

notebooks/bike_repositioning/interact_with_environment.ipynb, notebooks/container_inventory_management/interact_with_environment.ipynb, notebooks/vm_scheduling/interact_with_environment.ipynb
Fix typos of notebooks, including CIM, Citi Bike, and VM scenarios.
- OS:
=> Fix noteboook typos

scripts/build_sdist.bat, scripts/build_sdist.sh, setup.py
Currently tests folder was included in the distributed packages, but we should ignore it.
- OS:
=> Bug fix: Exclude tests folder from package.

maro/simulator/scenarios/vm_scheduling/topologies/azure.2019.10k.oversubscription/config.yml, maro/simulator/scenarios/vm_scheduling/topologies/azure.2019.10k/config.yml, maro/simulator/scenarios/vm_scheduling/topologies/azure.2019.336k.oversubscription.multi_clusters/config.yml, maro/simulator/scenarios/vm_scheduling/topologies/azure.2019.336k.oversubscription/config.yml
add topologies for over-subscription and multi-cluster to be compatible with the previous topologies
- OS:
=> V0.2 vm region topo

maro/backends/np_backend.pyx, maro/simulator/core.py, scripts/compile_cython.sh
Fix bugs for snapshot dump, due to property name_mapping_file_path has been removed.
- [248](https://github.com/microsoft/maro/issues/248)
- OS:
=> V0.2 remove props from be

examples/vm_scheduling/rule_based_algorithm/bin_packing.py, examples/vm_scheduling/rule_based_algorithm/launcher.py, examples/vm_scheduling/rule_based_algorithm/rule_based_algorithm.py
1. Fix coding style to pass the Pytlint check.
2. Remove unused import function.
- OS:
=> V0.2 vm algorithm style

docs/source/scenarios/vm_scheduling.rst
1. Add VM data preparation doc
- OS:
=> Master vm doc - data preparation

maro/backends/_raw_backend_.pyx, maro/backends/backend.pxd, maro/backends/backend.pyx, maro/backends/frame.pyx, maro/backends/raw/node.cpp, maro/backends/raw/node.h, maro/backends/raw/snapshotlist.cpp, maro/backends/raw/snapshotlist.h, maro/backends/raw_backend.pyx, setup.py, tests/test_env.py, tests/test_frame.py, tests/test_snapshot.py
Fix issues for dynamic backend.
This PR contains changes:
1. bug fix: dynamic backend slot number not correct after reset
2. bug fix: value is interrupt if one node contains multiple list attribute
3. changes: snapshot query result  default value set to 0 instead nan, make it align with static backend
4. bug fix: on windows compiling fail due to cannot find max function.
- OS:
=> Dynamic backend issues fix.

README.md
update the installation from source steps:
- remove the link to pip install editable
- add the command of git clone
- add/modify the notes of installation methods
- OS:
=> update the installation from source steps

examples/supply_chain/config.yml, examples/supply_chain/env_wrapper.py, examples/supply_chain/single_thread_launcher.py, examples/supply_chain/topologies/test/config.yml
=> fix issues that stock is empty.

examples/supply_chain/render_tools.py, maro/simulator/scenarios/supply_chain/units/simplemanufacture.py, maro/simulator/scenarios/supply_chain/world.py
=> V0.2 sc 0506 fix

maro/simulator/scenarios/supply_chain/units/consumer.py
=> bug fix: consumer does not reset order cost

examples/cim/dqn/config/training_config.py, examples/cim/dqn/main.py, maro/communication/proxy.py, maro/rl/training/actor.py, maro/rl/training/actor_proxy.py, maro/rl/training/learner.py, tests/communication/test_rejoin.py
=> add close() function for Proxy

maro/simulator/scenarios/supply_chain/business_engine.py
=> remove cached action after reset

maro/simulator/scenarios/supply_chain/units/unitbase.py
=> reset action after reset

maro/rl/__init__.py, maro/rl/env_wrapper/__init__.py, maro/rl/experience/__init__.py
=> update rl init

setup.py
New changes in our pipeline require a higher version of numpy.
- OS:
=> Update setup.py for new dependencies

maro/cli/maro_real_time_vis/back_end/vis_app/requirements.txt, maro/requirements.build.txt, notebooks/requirements.nb.txt, pyproject.toml, requirements.dev.txt, tests/requirements.test.txt
=> update numpy version limit

maro/simulator/scenarios/cim/business_engine.py, maro/simulator/scenarios/cim/vessel.py
Add the attributes: is_parking, loc_port_idx to vessel
- OS:
=> add vessel attributes: is_parking and loc_port_idx

maro/simulator/abs_core.py
- Add a property `business_engine` to `AbsEnv`
- OS:
=> add BE property to AbsEnv

maro/rl/training/trajectory.py
This addresses the issue in the trjactory interface described in #373 
- #373 
- [x ] Non-breaking bug fix
- [x ] RL toolkit
- OS:
- [x ] Linux
- [x ] 3.7
=> adjust interface to reflect actual signature

setup.py
add dataclasses requirement to setup
- OS:
=> add dataclasses requirement to setup

docs/source/examples/multi_agent_dqn_cim.rst, docs/source/scenarios/citi_bike.rst, examples/vm_scheduling/rule_based_algorithm/README.md, maro/cli/grass/lib/services/master_agent/agent.py, maro/cli/utils/node_admin.py, maro/cli/utils/web_terminal/terminal-srv.py, maro/data_lib/cim/vessel_sailing_plan_wrapper.py, maro/event_buffer/event_buffer.py, maro/simulator/scenarios/cim/business_engine.py, maro/utils/utils.py, maro/vector_env/vector_env.py, scripts/import_cim_dumps.py
fixing typos spelling grammar on ```microsoft/maro```, grammar reference using [Miriam webster](https://www.merriam-webster.com/)
- [378](#378)
- OS:
=> fix: fixing spelling grammarr

docs/source/key_components/data_model.rst, maro/cli/envs/list_available.py, maro/cli/maro_real_time_vis/start_maro_geo_vis.py, maro/data_lib/cim/cim_data_container.py, maro/simulator/scenarios/cim/matrix.py, tests/test_event_buffer.py, tests/test_snapshot.py
minor fixing typo misspelling grammar, fixing with reference from [dictionary merriam webster](https://www.merriam-webster.com/)
- [381](#381)
- OS:
=> minor fixing

maro/cli/maro_real_time_vis/back_end/vis_app/app.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_decision.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_exp_info.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_order.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_port.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/request_vessel.py, maro/cli/maro_real_time_vis/back_end/vis_app/data_process/request/utils.py, maro/cli/maro_real_time_vis/start_maro_geo_vis.py
**Fix Geo vis IP address & SQL logic bugs.**
As reported in [352](https://github.com/microsoft/maro/issues/352), the Geo vis frontend app could not access the database if the database is deployed on a remote server. The root cause is that both the frontend and backend app run in local mode (can only be accessed from the same machine), therefore all external access will be blocked. This PR fixes these bugs.
This PR also fixes some related SQL logic bugs. The original SQL logic fails to get the data under some corner cases.
- [352](https://github.com/microsoft/maro/issues/352)
- OS:
=> Fix Geo vis IP address & SQL logic bugs.

.github/workflows/test.yml, setup.py
add python version 3.8, 3.9 to setup.py and update the github test workflow respectively.
- OS:
=> add higher python version

maro/data_lib/cim/utils.py, maro/simulator/utils/sim_random.py, tests/cim/test_cim_scenario.py
Add `clear()` function to class `SimRandom` so that the user could explicitly refresh a `SimRandom` object.
- OS:
=> Add `clear()` function to class `SimRandom`

examples/oncall_routing/hello.py, maro/data_lib/oncall_routing/__init__.py, maro/data_lib/oncall_routing/data_loader.py, maro/data_lib/oncall_routing/not_used_data_cntr.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/__init__.py, maro/simulator/scenarios/oncall_routing/arrival_time_predictor.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/carrier_status.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/order.py, maro/simulator/scenarios/oncall_routing/utils.py
- remove some files from *scenario* folder to *data_lib* folder
- rename `carrier_status` to `carrier`
- add comments for license
- OS:
=> re-organize file structure

examples/oncall_routing/hello.py, maro/data_lib/oncall_routing/data_loader.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/__init__.py, maro/simulator/scenarios/oncall_routing/arrival_time_predictor.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/coordinate.py, maro/simulator/scenarios/oncall_routing/frame_builder.py, maro/simulator/scenarios/oncall_routing/order.py, maro/simulator/scenarios/oncall_routing/route.py, maro/simulator/scenarios/oncall_routing/topologies/example/config.yml, maro/simulator/scenarios/oncall_routing/utils.py
- add frame nodes;
- replace route_number with route_name;
- **business engine logic pending check and update**
- OS:
=> add frame nodes; replace route_number with route_name

maro/rl_v3/policy_trainer/__init__.py, maro/rl_v3/policy_trainer/abs_trainer.py, maro/rl_v3/policy_trainer/discrete_maddpg.py, maro/rl_v3/policy_trainer/maddpg.py, maro/rl_v3/tmp_example_multi/config.py, maro/rl_v3/tmp_example_multi/policies.py
Implement `MADDPG` algorithm and test the centralized & decentralized mode.
- OS:
=> Rl v3 maddpg

examples/oncall_routing/hello.py, maro/data_lib/oncall_routing/data_loader.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/duration_time_predictor.py, maro/simulator/scenarios/oncall_routing/order.py, maro/simulator/scenarios/oncall_routing/topologies/example/config.yml
- Add order processing logic
- Add env metrics
- 
- OS:
=> Add order processing logic

maro/data_lib/oncall_routing/__init__.py, maro/data_lib/oncall_routing/data_loader.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/order.py, maro/simulator/scenarios/oncall_routing/route.py, maro/simulator/scenarios/oncall_routing/topologies/example/config.yml
=> Non-functional refactor

.gitignore, examples/oncall_routing/hello.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/coordinate.py, maro/simulator/scenarios/oncall_routing/order.py, maro/simulator/scenarios/oncall_routing/topologies/example/config.yml
- Add waiting for order processing logic;
- Add order processing event;
- add carrier departure event;
- add order terminated logic;
- implement BE reset logic;
- OS:
=> Improve order transition logic and add events accordingly; Implement BE reset logic

maro/data_lib/oncall_routing/data_loader.py, maro/simulator/scenarios/oncall_routing/business_engine.py
=> Add data loader reset & more comments & insert location check.

examples/oncall_routing/greedy.py, examples/oncall_routing/hello.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/__init__.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/plan_element.py, maro/simulator/scenarios/oncall_routing/route.py
- update OncallRoutingPayload implementation
- fix sample oncall generator coordinate type issue
- add greedy example
- OS:
=> fix sample oncall generator coordinate type issue; add greedy example

examples/oncall_routing/greedy.py, examples/oncall_routing/uniformly.py, maro/simulator/scenarios/oncall_routing/business_engine.py
- Add randomly assignment policy
- Add order status check before departure; remove the terminated ones
- Remove agent idx list from BE
- OS:
=> Add order status check before departure, remove the terminated ones; Add randomly assignment policy

examples/oncall_routing/greedy.py, examples/oncall_routing/uniformly.py, maro/data_lib/oncall_routing/__init__.py, maro/data_lib/oncall_routing/data_loader.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/carrier.py, maro/simulator/scenarios/oncall_routing/common.py, maro/simulator/scenarios/oncall_routing/coordinate.py, maro/simulator/scenarios/oncall_routing/duration_time_predictor.py, maro/simulator/scenarios/oncall_routing/topologies/example/config.yml
=> Several BE changes

maro/data_lib/oncall_routing/data_loader.py, maro/data_lib/oncall_routing/oncall_order_generator.py, maro/simulator/scenarios/oncall_routing/business_engine.py
=> Modify order processing & processing time logic

examples/oncall_routing/greedy.py, examples/oncall_routing/hello.py, examples/oncall_routing/uniformly.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/duration_time_predictor.py
- update env reset issue
- minor update to duration predictor
- update the tick used to estimate the duration to next stop
- OS:
=> Oncall routing/simulator

maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/duration_time_predictor.py, maro/simulator/scenarios/oncall_routing/plan_element.py
…dDurationPredictor into ActualDurationSampler
- OS:
=> EstimatedDurationPredictor related refinement

examples/oncall_routing/simple_manual.md
=> Feature & action document

examples/oncall_routing/greedy.py, examples/oncall_routing/hello.py, examples/oncall_routing/rl/env_sampler.py, examples/oncall_routing/rl/state_shaping_utils.py, examples/oncall_routing/uniformly.py, maro/simulator/scenarios/oncall_routing/__init__.py
=> add env sampler and state shaping utils for on call routing scenario

examples/oncall_routing/rl/state_shaping_utils.py
=> add time indepdent predictor-based state shaping utils

examples/oncall_routing/greedy.py, examples/oncall_routing/greedy_with_time_window.py, examples/oncall_routing/uniformly.py, examples/oncall_routing/utils.py
=> Refine be & decision event logics; Add greedy_with_time_window baseline;

examples/oncall_routing/greedy.py, examples/oncall_routing/greedy_with_time_window.py, examples/oncall_routing/hello.py, examples/oncall_routing/simple_manual.md, examples/oncall_routing/uniformly.py, examples/oncall_routing/utils.py, maro/simulator/scenarios/oncall_routing/business_engine.py, maro/simulator/scenarios/oncall_routing/common.py
- Add PostponeAction into the BE
- Update examples and manual respectively
- OS:
=> Add PostponeAction into oncall routing scenario

maro/rl_v3/training/algorithms/ac.py, maro/rl_v3/training/algorithms/ddpg.py, maro/rl_v3/training/algorithms/dqn.py, maro/rl_v3/training/algorithms/maddpg.py, maro/rl_v3/training/trainer.py, maro/rl_v3/training/trainer_manager.py, maro/rl_v3/utils/transition_batch.py
=> MADDPG performance bug fix

maro/README.rst, maro/data_lib/cim/cim_data_container_helpers.py, maro/simulator/core.py, maro/simulator/scenarios/abs_business_engine.py, maro/simulator/scenarios/cim/business_engine.py, maro/simulator/scenarios/citi_bike/business_engine.py, maro/simulator/scenarios/supply_chain/business_engine.py, maro/simulator/scenarios/vm_scheduling/business_engine.py
=> Change `Env.set_seed()` logic

examples/rl/cim/algorithms/ac.py, examples/rl/cim/algorithms/dqn.py, examples/rl/cim/env_sampler.py, examples/rl/vm_scheduling/algorithms/ac.py, examples/rl/vm_scheduling/algorithms/dqn.py, examples/rl/vm_scheduling/config.py, examples/rl/vm_scheduling/env_sampler.py, maro/rl/exploration/scheduling.py, maro/rl/model/abs_net.py, maro/rl/model/multi_q_net.py, maro/rl/model/policy_net.py, maro/rl/model/q_net.py, maro/rl/model/v_net.py, maro/rl/policy/abs_policy.py, maro/rl/policy/discrete_rl_policy.py, maro/rl/rollout/env_sampler.py, maro/rl/training/algorithms/ac.py, maro/rl/training/algorithms/ddpg.py, maro/rl/training/algorithms/dqn.py, maro/rl/training/algorithms/maddpg.py, maro/rl/training/replay_memory.py, maro/rl/training/train_ops.py, maro/rl/training/trainer.py, maro/rl/training/trainer_manager.py, maro/rl/utils/__init__.py, maro/simulator/scenarios/vm_scheduling/business_engine.py
=> RL V3 example update follow ups

docs/source/key_components/rl_toolkit.rst, examples/rl/cim/algorithms/ac.py, examples/rl/cim/algorithms/ppo.py, examples/rl/cim/config.py, examples/rl/cim/policy_trainer.py, maro/rl/training/algorithms/__init__.py, maro/rl/training/algorithms/ac.py, maro/rl/training/algorithms/base/__init__.py, maro/rl/training/algorithms/base/ac_ppo_base.py, maro/rl/training/algorithms/ppo.py
=> Split AC & PPO

docs/source/key_components/rl_toolkit.rst, examples/cim/rl/algorithms/ppo.py, examples/supply_chain/rl/algorithms/dqn.py, examples/supply_chain/rl/algorithms/ppo.py, examples/supply_chain/rl/env_sampler.py, examples/vm_scheduling/rl/algorithms/ac.py, examples/vm_scheduling/rl/algorithms/dqn.py, examples/vm_scheduling/rl/env_sampler.py, maro/rl/training/algorithms/ac.py, maro/rl/training/algorithms/base/ac_ppo_base.py, maro/rl/training/algorithms/maddpg.py, maro/rl/training/algorithms/ppo.py
1. Added refs for RL algos.
2. Removed obsolete "device" parameters from various examples;
- OS:
=> Refs for RL algorithms

maro/rl/training/algorithms/base/ac_ppo_base.py, maro/rl/utils/transition_batch.py
=> Preprocess old logps before update actor

examples/supply_chain/simple_random_example.py
=> Simple SC random script

examples/cim/rl/algorithms/ac.py, examples/cim/rl/algorithms/dqn.py, examples/cim/rl/config.py, examples/cim/rl/policy_trainer.py, examples/supply_chain/rl/__init__.py, examples/supply_chain/rl/algorithms/dqn.py, examples/supply_chain/rl/algorithms/ppo.py, examples/supply_chain/rl/algorithms/rule_based.py, examples/supply_chain/rl/policies.py, examples/vm_scheduling/rl/algorithms/ac.py, examples/vm_scheduling/rl/algorithms/dqn.py, examples/vm_scheduling/rl/config.py, maro/rl/rollout/env_sampler.py, maro/rl/rollout/worker.py, maro/rl/training/algorithms/base/ac_ppo_base.py, maro/rl/training/algorithms/ddpg.py, maro/rl/training/algorithms/dqn.py, maro/rl/training/trainer.py, maro/rl/training/training_manager.py, maro/rl/training/worker.py, maro/rl/workflows/main.py
=> Test PPO on CIM

examples/supply_chain/common/balance_calculator.py, examples/supply_chain/rl/agent_state.py, examples/supply_chain/rl/env_sampler.py, maro/simulator/scenarios/supply_chain/facilities/facility.py, maro/simulator/scenarios/supply_chain/facilities/retailer.py, maro/simulator/scenarios/supply_chain/objects.py, maro/simulator/scenarios/supply_chain/topologies/sample/config.yml, maro/simulator/scenarios/supply_chain/units/consumer.py, maro/simulator/scenarios/supply_chain/units/distribution.py, maro/simulator/scenarios/supply_chain/units/manufacture.py, maro/simulator/scenarios/supply_chain/units/product.py, maro/simulator/scenarios/supply_chain/units/vehicle.py, maro/simulator/scenarios/supply_chain/world.py
=> Move balance calculator inside SCBE

examples/supply_chain/rl/algorithms/rule_based.py, examples/supply_chain/rl/config.py, examples/supply_chain/rl/env_sampler.py, examples/supply_chain/rl/or_agent_state.py, examples/supply_chain/rl/policies.py, examples/supply_chain/rl/rl_agent_state.py, maro/rl/rollout/env_sampler.py, maro/simulator/scenarios/supply_chain/facilities/facility.py
…use List[state] as input
- Move OR state shaper to an independent file
- Update OR policies to use List[state] as input
- OS:
=> Update OR policies and env sampler workflow

maro/data_lib/supply_chain/__init__.py, maro/data_lib/supply_chain/preprocess_data_file.py, maro/simulator/scenarios/supply_chain/datamodels/seller.py, maro/simulator/scenarios/supply_chain/units/seller.py, maro/simulator/scenarios/supply_chain/world.py
=> Add `PreprocessedFileDemandSimpleSampler` and `PreprocessedFileDemandStreamSampler`

examples/supply_chain/common/balance_calculator.py, examples/supply_chain/rl/sc_state_in_maro.md, maro/simulator/scenarios/supply_chain/business_engine.py, maro/simulator/scenarios/supply_chain/datamodels/seller.py, maro/simulator/scenarios/supply_chain/facilities/facility.py, maro/simulator/scenarios/supply_chain/facilities/retailer.py, maro/simulator/scenarios/supply_chain/sku_dynamics_sampler.py, maro/simulator/scenarios/supply_chain/topologies/plant/config.yml, maro/simulator/scenarios/supply_chain/units/__init__.py, maro/simulator/scenarios/supply_chain/units/seller.py
- Add price update module to facility before each step (dynamic price support)
- remove price from seller data model
- OS:
=> Dynamic price supporting

examples/supply_chain/simple_random_example.py, maro/simulator/scenarios/supply_chain/actions.py, maro/simulator/scenarios/supply_chain/business_engine.py, maro/simulator/scenarios/supply_chain/datamodels/consumer.py, maro/simulator/scenarios/supply_chain/datamodels/distribution.py, maro/simulator/scenarios/supply_chain/datamodels/manufacture.py, maro/simulator/scenarios/supply_chain/datamodels/product.py, maro/simulator/scenarios/supply_chain/datamodels/storage.py, maro/simulator/scenarios/supply_chain/facilities/facility.py, maro/simulator/scenarios/supply_chain/topologies/plant/config.yml, maro/simulator/scenarios/supply_chain/topologies/sample/config.yml, maro/simulator/scenarios/supply_chain/units/consumer.py, maro/simulator/scenarios/supply_chain/units/distribution.py, maro/simulator/scenarios/supply_chain/units/manufacture.py, maro/simulator/scenarios/supply_chain/units/product.py, maro/simulator/scenarios/supply_chain/units/seller.py, maro/simulator/scenarios/supply_chain/units/storage.py, maro/simulator/scenarios/supply_chain/units/unitbase.py, maro/simulator/scenarios/supply_chain/world.py, tests/data/supply_chain/case_01/config.yml, tests/data/supply_chain/case_02/config.yml, tests/data/supply_chain/case_03/config.yml, tests/supply_chain/test_supply_chain.py
- update the definition of manufacture leading time
- change action dispatch logic
- update unit tests
- OS:
=> Sc leading time logic fix

examples/rl/run_rl_example.py, examples/supply_chain/rl/algorithms/base_policy_data_loader.py, examples/supply_chain/rl/algorithms/base_stock_policy.py, examples/supply_chain/rl/config.py, examples/supply_chain/rl/env_sampler.py, examples/supply_chain/rl/or_agent_state.py, examples/supply_chain/rl/rl_component_bundle.py
* Add base stock policy
* Support load from file and from history
=> base stock policy

examples/supply_chain/rl/algorithms/base_policy_data_loader.py, examples/supply_chain/rl/algorithms/base_stock_policy.py, examples/supply_chain/rl/or_agent_state.py
=> * rename and use sku id for index in base stock oracle

examples/supply_chain/rl/algorithms/base_policy_data_loader.py, examples/supply_chain/rl/algorithms/base_stock_policy.py, examples/supply_chain/rl/or_agent_state.py
=> Revert "* rename and use sku id for index in base stock oracle"

examples/supply_chain/rl/config.py, examples/supply_chain/rl/env_sampler.py, maro/simulator/scenarios/supply_chain/actions.py, maro/simulator/scenarios/supply_chain/business_engine.py, maro/simulator/scenarios/supply_chain/order.py, maro/simulator/scenarios/supply_chain/units/consumer.py, maro/simulator/scenarios/supply_chain/units/distribution.py, maro/simulator/scenarios/supply_chain/units/storage.py, tests/supply_chain/test_supply_chain_consumer_unit.py, tests/supply_chain/test_supply_chain_distribution_unit.py, tests/supply_chain/test_supply_chain_state_only.py
- Add order expiration logic
- Add order statistics to env metrics (pending scheduled, expired order num, delayed scheduling, ...)
- Update order class definition, and enrich related logic
- Add order statistics to ConsumerUnit & DistributionUnit, and update processing logic
- Fix unit test issues
- OS:
=> Update Order definition and related logic & metrics

maro/cli/inspector/citi_bike_dashboard.py, maro/cli/inspector/dashboard_helper.py
try fix citi bike hello world dashboard
- OS:
=> try fix citi bike hello world dashboard

docs/source/key_components/data_model.rst
=> Refine data model doc

tests/rl/algorithms/ac.py, tests/rl/algorithms/ppo.py, tests/rl/algorithms/sac.py, tests/rl/gym_wrapper/config.py, tests/rl/gym_wrapper/env_sampler.py, tests/rl/gym_wrapper/rl_component_bundle.py, tests/rl/gym_wrapper/simulator/business_engine.py, tests/rl/performance.md
=> update for some PR comments; Add a MARKDOWN file

.github/workflows/build_wheel.yml, setup.py
1. Fix issue on manylinux by avoid installing additional packages.
2. Move source package building to Windows, as it will cause permission issue on linux now(not sure why).
[Here](https://github.com/chaosddp/maro/actions/runs/4414318592#artifacts) is the result after apply these changes.
- OS:
=> Update build wheel action

maro/rl/policy/discrete_rl_policy.py
fix DiscreteRLPolicy set_state bug
- OS:
=> fix DiscreteRLPolicy set_state bug

.github/workflows/build_wheel.yml
Fix PyPI build & upload verification issue
- OS:
=> Master.update build
